# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  一百零八天
subtitle: 分享时光,分享技术。
name: 咸阳道主
email: day108@126.com
description: 这里是是咸阳东道主的生活技术分享博客。内容涵盖小说，生活故事、Java后端技术、Spring Boot、Spring Cloud、微服务架构、大数据演进、高可用架构、中间件使用、系统监控等相关的研究与知识分享。
keywords: 一百零八天,www.108day.com,https://108day.github.io,day108@126.com,分享时光,分享技术,Spring,Spring Boot,Spring Cloud,MongoDB,Java,Jvm,Docker,生活故事,架构,大数据,一线,开发者,编程,代码,开源,IT网站,物联网,Developer,Programmer,Coder,Geek,IT技术博客,Java,C/C++,Python,Shell
encoding: "utf-8"
favicon: favicon.png 

#repository: ityouknow/ityouknow.github.io
#github_url: https://github.com/ityouknow
#cnblog_url: http://www.cnblogs.com/ityouknow
#url: http://www.ityouknow.com
#enforce_ssl: ityouknow.com
repository: 108day/108day.github.io
github_url: https://github.com/108day
url: https://108day.github.io

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:

  -
    href: /
    label: Home

  -
    href: /jvm.html
    label: JVM
    
  -
    href: /data-structure.html
    label: 数据结构
    
  -
    href: /system-scurity.html
    label: 系统安全
    
  -
    href: /archives.html
    label: Archives

  -
    href: /link.html
    label: Link

  -
    href: /about.html
    label: About


# labels. my blog key words
labels:

  -
    href: #
    name: 资源

  -
    href: /novel.html
    name: 小说
    
  -
    href: /life.html
    name: 生活
    
  -
    href: /jvm.html
    name: JVM
  -
    href: /java.html
    name: JAVA   
  -
    href: /spring-boot.html
    name: Spring-Boot
    
  -
    href: /spring-cloud.html
    name: Spring-Cloud
    
  -
    href: /data-structure.html
    name: 数据结构

  -
    href: /mongodb.html
    name: MongoDB
    
  -
    href: /redis.html
    name: Redis
  
  -
    href: /arch.html
    name: 架构师
    
  -
    href: /big-data.html
    name: 大数据   
    
  -
    href: /internet_of_things.html  
    name: 物联网
    
  -
    href: /open-source.html
    name: Code   

# selected articles
classes:

  -
    href: /life.html
    name: 咸阳道主
    describe: 处处留心皆学问，人情练达即文章
  -
    href: /novel.html
    name: 我的小说
    describe: 人总要有点梦想，不然和咸鱼有什么区别
    
  -
    href: /arch.html
    name: 架构师之路
    describe: 架构师的自我修养
  -
    href: /java.html
    name: 万丈高楼平地起
    describe: 打好基础，练好内功
    
  -
    href: /jvm.html
    name: Jvm系列文章
    describe: Java之根基，Java程序员必学
  -
    href: /internet_of_things.html
    name: 物联网
    describe: 连接你我，连接世界
    
  -
    href: /spring-boot.html
    name: Spring-Boot
    describe: 最优秀的微服务解决方案落地产品，没有之一  
    
  -
    href: /spring-cloud.html
    name: Spring-Cloud
    describe: 微服务架构服务治理解决方案
  -
    href: /data-structure.html
    name: 数据结构
    describe: 程序 = 算法　+　数据结构
    
  -
    href: /protocol.html
    name: 网络协议
    describe: 网络可以畅通无阻就是因为协议的存在
    
# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, Redis, Redis, MongoDB, PHP, C/C++, Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 108day
# https://imsun.net/posts/gitment-comments/
gitment:
    owner: 108day
    repo: blog-comments
    oauth:
        client_id: 18c2d6d97d67926035b5
        client_secret: 1b157be502423178a234a36f92e1f1ee23008987
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 108day
    repo: blog-comments
    clientID: 1f02192554bde9b07bf8
    clientSecret: bc467ba8d75e23cc041adc841401382b6d41aa28
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
